### ISSUE TITLE
Orchid - Work in progress docs?

### ISSUE THREAD

**Issue by jbritain** [Vanilla-OS/documentation#109]
Obviously Orchid is still in beta, so it makes sense that the docs might not have made it to the site yet, but is there really no documentation for Orchid yet? An `orchid` branch for the repo with work in progress documentation would be handy to have, because a lot of the tools are nigh on impossible to use right now unless you've been involved in the development to some degree.

**Comment by mirkobrombin** [comment]
@kbdharun

**Comment by kbdharun** [comment]
> Obviously Orchid is still in beta, so it makes sense that the docs might not have made it to the site yet, but is there really no documentation for Orchid yet? An `orchid` branch for the repo with work in progress documentation would be handy to have, because a lot of the tools are nigh on impossible to use right now unless you've been involved in the development to some degree.

The current default branch is the tracking branch for Orchid docs (Kinetic has a seperate branch, which has been archived). The man pages have been ported to Orchid, the remaining tasks are to port the core docs for the same. I will do it in the forthcoming days (have been busy with Uni work the past few weeks, so no new progress in docs).

I have a few drafts lying around for some new pages about the images we have, etc. Will focus on upstreaming and porting them.

**Comment by jbritain** [comment]
Alright, fair enough.
