### ISSUE TITLE
Main text cut on phones and portrait aspect ratios

### ISSUE THREAD

**Issue by D-Maxwell** [Vanilla-OS/documentation#2]
Upon loading the VanillaOS docs on my phone, I noticed the main text was cut and unreadable on each and every page. Not only that, the navigation bar is taking the whole width of the page, but that isn't really the issue.
I, and a friend of mine, have both loaded the docs on our phones, on both Brave and Firefox for Android. I have also seen this behaviour on desktop (Brave for Windows) but only upon resizing the window to a very low aspect ratio.

**Comment by mirkobrombin** [comment]
fixed by https://github.com/Vanilla-OS/documentation/pull/3
