### ISSUE TITLE
Mark this repo as deprecated and clone voxelin/altdoc.

### ISSUE THREAD

**Issue by voxelin** [Vanilla-OS/documentation#71]
Hello, since this repo uses Jekyll for its documentation system, it may be hard to implement translations, plugins, change styles. I made a remake of this repo, which contains all the information (including translations), written on Docusaurus. Thank you.

**Comment by mirkobrombin** [comment]
We currently host the documentation on GitHub. How will be with docusaurus?

**Comment by kbdharun** [comment]
> We currently host the documentation on GitHub. How will be with docusaurus?

The person seem to suggest using netlify, more info on #docs-writing

**Comment by voxelin** [comment]
> We currently host the documentation on GitHub. How will be with docusaurus?

Thanks for your reply. I recommend you seeing this article: https://docusaurus.io/docs/deployment#deploying-to-github-pages. In short, github pages are also supported by this framework.

**Comment by voxelin** [comment]
To be clear, i would also recommend you using Netlify, as it is free service that provides more advanced functionality than Github Pages do. As an example, with Docusaurus deployments will be automatically checked for errors in Markdown files (Broken links, invalid syntax, etc.). Also, Netlify does provide Netlify Edge Functions, that allow some back-end stuff and regional redirects (Useful for i18n). Sorry for such a long-read text but I hope you will agree on this changes. Thank you for your time.

**Comment by mirkobrombin** [comment]
I feel comfortable with Github. To make this happen we need to configure the github action for the deployment.

**Comment by voxelin** [comment]
> I feel comfortable with Github. To make this happen we need to configure the github action for the deployment. And maybe open a PR.

If i configure it for your repo, will you merge it with all the changes with docusaurus?

**Comment by voxelin** [comment]
See #73. Thanks.
