### ISSUE TITLE
Change the Framework from Jekyll To Docusaurus.

### ISSUE THREAD

**Issue by voxelin** [Vanilla-OS/documentation#74]
Hello. Since your documentation is using Jekyll Ruby Framework, It may be difficult to make changes to the content, provide new translations, customize website’s look and so on, so i made a remake of your Documentation, written on Docusaurus. Below, you would see some pros and cons that will help you to make the decision. Thank you in advance.

### Pros:

- Create user translations using Crowdin. (Also, easier to provide in-repo translations, because of project folder structure, which you can see [here](https://github.com/voxelin/documentation).)
- Ability to create new styles for the website, customize color theme (using simple json).
- Ability to download new plugins using `yarn install @docusaurus/plugin_name`, including Search-plugin, automatic Markdown generation, etc.
- New technologies. Docusaurus is a framework that works on JavaScript, allowing you to use any edge hosting (`Vercel`, `Netlify`,  `Deno Deploy`) and consume minimum amount of RAM on VPS/VDS.

### Cons:

- Slower builds of pages on GitHub Actions:
    - Building of entire website (including all the i18n translations) consume ~1.9 minutes.

You can check the deployed version [here](https://doc.ieljit.lol), and the repository with the source code [here](https://github.com/voxelin/documentation).

**Comment by pietrodicaprio** [comment]
What about [GitBook](https://www.gitbook.com/)? They already provided us a license for Bottles that can be used for Vanilla OS too (or we can ask to provide Vanilla OS of a dedicated license).
GitBook allows us to avoid all the management with GH Pages, Actions, and so on while providing customization and integrations.

**Comment by mirkobrombin** [comment]
> What about [GitBook](https://www.gitbook.com/)? They already provided us a license for Bottles that can be used for Vanilla OS too (or we can ask to provide Vanilla OS of a dedicated license). GitBook allows us to avoid all the management with GH Pages, Actions, and so on while providing customization and integrations.

Agree with this, less headache.

**Comment by kbdharun** [comment]
> What about [GitBook](https://www.gitbook.com/)? They already provided us a license for Bottles that can be used for Vanilla OS too (or we can ask to provide Vanilla OS of a dedicated license). GitBook allows us to avoid all the management with GH Pages, Actions, and so on while providing customization and integrations.

Yeah, that seems to be a better option.

**Comment by voxelin** [comment]
As 3 days later i see no change on the website, neither my option or GitBook were chosen, i propose merging my repo real quick, as it is fully working on GitHub Pages. Or, on the other side, i'd close the 3 issues and that's all. Thank you!

**Comment by pietrodicaprio** [comment]
> As 3 days later i see no change on the website, neither my option or GitBook were chosen, i propose merging my repo real quick, as it is fully working on GitHub Pages. Or, on the other side, i'd close the 3 issues and that's all. Thank you!

The community is not made by a few. We allow time for contributors and community members to jump into the discussion.
As per the choice looks like that GitBook is a preferred option here for its semplicity in the management but it's not official yet.
We thank you in advance for rising the topic and the suggestions as those are going to improve what the community gets from the project!
