### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by xplosionmind** [Vanilla-OS/documentation#78]
In the “Multiple sources” section of `docs/apx/index.md` there is a link to `https://documentation.vanillaos.org/docs/vanilla-control-center`, which does not exist.

**Comment by kbdharun** [comment]
Will fix it. Pinging myself to check this later @kbdharun

**Comment by TheOne04** [comment]
This hasn't been fixed yet, can I contribute by creating a page for this and write a basic documentation for it?

**Comment by TheOne04** [comment]
Sure!
